syntax enable
set nocompatible
set relativenumber
set mouse=a
set ai
"set bg=light	this is for low-light environments
set bg=dark	" this is for daytime
set incsearch
set showmatch
set clipboard=unnamedplus
set mouse=a
set backspace=indent,eol,start
set showmode
set showcmd
set laststatus=2
set splitbelow splitright
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

"set path+=** this will get you in trouble, use with caution
set wildmenu
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3

"START SEC:	KEYMAPS
let mapleader = ","
nnoremap C :co
nnoremap M :move
nnoremap <C-w>t <C-w>gt
nnoremap S :%s//g<Left><Left>
nnoremap <silent>:srcfg :so ~/.vimrc<CR>
nnoremap <C-t> :tabnew<CR>
" Ctrl + s = save
nnoremap <silent><C-s> :w<CR>
inoremap <silent><C-s> <C-o>:w<CR>

nnoremap <silent> <F1> "_dd
inoremap <F1> <C-o>"_dd

nnoremap <Leader>cd :execute("chdir ".escape(expand("%:p:h"), ' '))<CR>
"END SEC
"START SEC: auto commands
aug srcfg
	au!
	au BufWritePost ~/.vimrc so ~/.vimrc
	au BufWritePre * %s/\s\+$//e
	au InsertEnter * :set number relativenumber
	au InsertLeave * :set norelativenumber number
"	au BufEnter * exe execute("chdir ".escape(expand("%:p:h"), ' '), "silent!")
aug END
"END SEC

" START SEC: PATHOGEN
execute pathogen#infect()
Helptags
"END SEC
